#Server
server:
  encoding:
    charset: UTF-8
    enabled: true
    force : true
  port: 80


spring:
  config:
    import:
      classpath:application-aws.yml
  mvc:
    static-path-pattern: /static/**
  #DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/certblockDB?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: certblock
    password: 1234
  #JPA
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        use-new-id-generator-mappings:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

#log
logging:
  level:
    org.hibernate.type.descriptor.sql: trace

app:
  aes128:
    secret-key: ${AES128_SECRETKEY}
  sens:
    access-key: ${SENS_ACCESSKEY}
    service-key: ${SENS_SERVICEKEY}
    secret-key: ${SENS_SECRETKEY}
    from-num: ${SENS_FROMNUM}

ethereum:
  ethereumFrom: "0x3861ce91ED1b8dE311F025923F711EA07a8501c1"
  contract: "0x28749c09318D8eef441BB3e0eD5F759C2CCbbf1f"
  privateNetworkUrl: http://13.125.144.163:7540
